Repository mteu/typo3-typed-extconf, pull requests merged in 2025-07, with the labels that each got.

#2 [DOCS] Add SECURITY and CONTRIBUTING paragraphs
  README.md
  SECURITY.md
Labels: documentation

#5 [FEATURE] Add backward compatibility for PHP 8.2
  .github/workflows/tests.yaml
  Tests/Unit/Provider/TypedExtensionConfigurationProviderTest.php
  composer.json
  composer.lock
  phpstan.inc.neon
  phpstan.neon
Labels: enhancement

#4 [FEATURE] Support TYPO3 v12.4 LTS
  .github/workflows/tests.yaml
  Tests/Unit/Provider/TypedExtensionConfigurationProviderTest.php
  composer.json
  composer.lock
  phpstan.inc.neon
  phpstan.neon
Labels: enhancement

#6 [FEATURE] Support TYPO3 v12.4 LTS
  .github/composer/composer.typo3-v12.json
  .github/workflows/tests.yaml
  composer.json
  composer.lock
Labels: enhancement

#7 [!!!][TASK] Drop default value in ExtConfProperty
  Classes/Attribute/ExtConfProperty.php
  Classes/Provider/TypedExtensionConfigurationProvider.php
  Documentation/developer-guide.md
  README.md
  Tests/Unit/Fixture/ApiConfiguration.php
  Tests/Unit/Fixture/ComplexTestConfiguration.php
  Tests/Unit/Fixture/MultiNestedTestConfiguration.php
  Tests/Unit/Fixture/NestedTestConfiguration.php
  Tests/Unit/Fixture/RequiredTestConfiguration.php
  Tests/Unit/Fixture/SecurityConfiguration.php
  Tests/Unit/Fixture/SimpleTestConfiguration.php
Labels: breaking

#11 [FEATURE] Allow injection of custom `TreeMapper` via DI
  Classes/Mapper/TreeMapperFactory.php
  Classes/Provider/TypedExtensionConfigurationProvider.php
  Configuration/Services.php
  Documentation/command-guide.md
  Documentation/developer-guide.md
  README.md
  Tests/Unit/DependencyInjection/AutoconfigurationTest.php
  Tests/Unit/Provider/TypedExtensionConfigurationProviderTest.php
Labels: enhancement

#12 [TASK] Set DI visibility of services
  Configuration/Services.php
Labels: maintenance

#13 [BUGFIX] Remove redundant service registration for TreeMapperFactory
  Configuration/Services.php
  Tests/Unit/DependencyInjection/AutoconfigurationTest.php
Labels: bug

#14 [DOCS] Document custom `TreeMapper` configuration
  Documentation/developer-guide.md
Labels: documentation

#30 [TASK] Refactor GitHub CGL and Test workflows
  .gitattributes
  .github/composer/composer.typo3-v12.json
  .github/workflows/cgl.yaml
  .github/workflows/tests.yaml
  .gitignore
  Tests/CGL/.gitignore
  Tests/CGL/composer-dependency-analyser.php
  Tests/CGL/composer.json
  Tests/CGL/php-cs-fixer.php
  Tests/CGL/phpstan-baseline.neon
  Tests/CGL/phpstan.neon
  Tests/CGL/rector.php
  composer.json
  composer.lock
Labels: maintenance

#33 [TASK] Remove ineffective settings workflow
  .github/settings.yaml
Labels: maintenance

#45 [TASK] Rephrase license header according to TYPO3 coding standards
  Classes/Attribute/ExtConfProperty.php
  Classes/Attribute/ExtensionConfig.php
  Classes/Command/GenerateConfigurationCommand.php
  Classes/Exception/ConfigurationException.php
  Classes/Exception/SchemaValidationException.php
  Classes/Generator/ConfigurationClassGenerator.php
  Classes/Mapper/MapperFactory.php
  Classes/Mapper/TreeMapperFactory.php
  Classes/Parser/ExtConfTemplateParser.php
  Classes/Provider/ExtensionConfigurationProvider.php
  Classes/Provider/TypedExtensionConfigurationProvider.php
  Configuration/Services.php
  Tests/CGL/composer-dependency-analyser.php
  Tests/CGL/php-cs-fixer.php
  Tests/CGL/rector.php
  Tests/Unit/Attribute/ExtConfPropertyTest.php
  Tests/Unit/DependencyInjection/AutoconfigurationTest.php
  Tests/Unit/Fixture/Configuration/ApiConfiguration.php
  Tests/Unit/Fixture/Configuration/ComplexTestConfiguration.php
  Tests/Unit/Fixture/Configuration/ErrorTestConfiguration.php
  Tests/Unit/Fixture/Configuration/InvalidExtensionConfigTestConfiguration.php
  Tests/Unit/Fixture/Configuration/MultiNestedTestConfiguration.php
  Tests/Unit/Fixture/Configuration/NestedTestConfiguration.php
  Tests/Unit/Fixture/Configuration/RequiredTestConfiguration.php
  Tests/Unit/Fixture/Configuration/SecurityConfiguration.php
  Tests/Unit/Fixture/Configuration/SimpleTestConfiguration.php
  Tests/Unit/Generator/ConfigurationClassGeneratorTest.php
  Tests/Unit/Mapper/TreeMapperFactoryTest.php
  Tests/Unit/Parser/ExtConfTemplateParserTest.php
  Tests/Unit/Provider/TypedExtensionConfigurationProviderTest.php
  ext_emconf.php
  packaging_exclude.php
Labels: maintenance

#44 [TASK] Add extension icon
  README.md
  Resources/Public/Icons/Extension.svg
  ext_emconf.php
Labels: maintenance

#47 [DOCS] Correct type for breaking changes in contribution guide
  CONTRIBUTING.md
Labels: documentation

#48 [BUGFIX] Make sure FQCNs are used in generated config classes
  Classes/Generator/ConfigurationClassGenerator.php
  Tests/Unit/Generator/ConfigurationClassGeneratorTest.php
Labels: bug
